# **Introduction**

Sebelum sebuah data dapat dianalisis atau digunakan untuk mengambil keputusan kebijakan tentu data tersebut perlu untuk diekstraksi terlebih dahulu. <b>Ekstraksi data</b> adalah sebuah proses pengumpulan atau pengambilan jenis data yang berbeda dari berbagai sumber, banyak di antaranya mungkin tidak terorganisir dengan baik atau tidak terstruktur sama sekali. Proses ini memungkinkan untuk mengkonsolidasikan, memproses, dan menyempurnakan data sehingga nantinya dapat disimpan di lokasi terpusat untuk diubah atau diproses lebih lanjut.

Python sebagai salah satu <i>tools</i> yang <i>powerful</i> untuk pengolahan data menyediakan berbagai <i>library</i> untuk mendukung proses ekstraksi data. Salah satu library paling banyak digunakan adalah <b>pandas</b>.

Pandas memungkinkan untuk membaca data dari berbagai jenis ekstensi seperti data yang bersumber dari database (sql), <i>excel</i> (<b>.xls</b> atau <b>.xlsx</b>), <i>separated value file</i> (<b>.csv</b>, <b>.tsv</b>, dsb) lalu merubahnya menjadi satu format struktur data yang sama yang disebut <b>DataFrame</b>. DataFrame inilah yang nantinya dapat kita lakukan proses <b>Data Manipulation</b><br><br>

<p align="center">
<img src="https://drive.google.com/uc?export=view&id=18NW3gMMTJjkwwpZX5TXi9DTteXxGAoxa" width="600" height="300">
<p align="center"><b>Gambar 1. Proses Ekstraksi Data dengan <i>pandas</i></b></p>

<br><br>
<p align="right"><sup>docs : <i><a href="https://shorturl.at/xyZ69">https://pandas.pydata.org/docs/user_guide/io.html</i></sup></a></p>

##**1. First Step : Pandas**

Untuk dapat menggunakan library pandas pada python, perlu untuk mengimpor library tersebut dengan cara mengetikan sintaks berikut

<p align="center"><code><b>import pandas as pd</b></code></p>

lalu jalankan (<i>run</i>) program.

<br><br>
<p align="left"><sup>docs : <i><a href="https://shorturl.at/kzG06">https://pandas.pydata.org/docs/getting_started/install.html</i></sup></a></p>

### 👨‍💻 Task 1.1

Ketikan kode `import pandas as pd` pada prompt dibawah ini lalu jalankan

In [134]:
# Write your code below here & exec!
import pandas as pd

### 👨‍💻 Task 1.2

Fungsi pd.set_option() di pandas digunakan untuk mengubah pengaturan tampilan (display options) dan perilaku global pandas saat bekerja di notebook, terminal, atau saat mencetak DataFrame. Sebagai contoh :   <br><br>   

* **Menampilkan seluruh isi DataFrame tanpa pemotongan**<br>`pd.set_option('display.max_rows', None)` -> Menampilkan seluruh baris tanpa pemotongan<br>`pd.set_option('display.max_columns', None)` -> Menampilkan seluruh kolom tanpa pemotongan<br><br>

* **Mengatur lebar kolom saat ditampilkan**<br>`pd.set_option('display.max_colwidth', None)` -> lebar maksimal tiap kolom (karakter)<br><br>

* **Mengatur angka dibelakang koma**<br>`pd.set_option('display.float_format', '{:.2f}'.format)` -> Tampilkan 2 angka di belakang koma<br><br>

Coba eksekusi sintaks tersebut dan lihat perbedaan tampilannya!

docs : _https://pandas.pydata.org/docs/reference/api/pandas.set_option.html_

In [135]:
# Eksekusi kedua sintaks berikut
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.float_format', '{:.2f}'.format)

# **Struktur Data Pandas**

* Terdapat dua struktur data utama pada library pandas yang disebut dengan Series dan DataFrame.
<p align="center">
<img src="https://datagy.io/wp-content/uploads/2022/12/Understanding-Pandas-Series-and-DataFrames-1024x576.png" width="550" height="289">
<p align="center"><b>Gambar 2. Series VS DataFrame</b></p>
<br>

* Gabungan beberapa Series yang mempunyai banyak baris yang sama dapat membentuk sebuah DataFrame atau berlaku sebaliknya pada sebuah DataFrame dapat dipecah (di-<i>slicing</i> satu kolom) membentuk sebuah Series.<br><br>

<p align="right"><sup>docs : <i><a href="https://shorturl.at/dezQY">http://pandas.pydata.org/docs/getting_started/intro_tutorials/01_table_oriented.html</i></sup></a></p>

##**2. Series**

* <a href="">Series</a> merupakan kolom dari sebuah tabel yang bersifat homogen atau mempunyai elemen dengan tipe data yang sejenis.

* Untuk membuat Series gunakan sintaks berikut

<p align="center"><code><b>pd.Series(data)</b></code></p>

<ul>
  data dapat berupa <i>array-like</i>, <i>Iterable</i>, <i>dict</i>, atau <i>scalar</i>
</ul>

<p align="right"><sup>docs : <i><a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html">https://pandas.pydata.org/docs/reference/api/pandas.Series.html</i></sup></a></p>

## **3. DataFrame**

* <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame">DataFrame</a> adalah struktur data 2 dimensi yang terdiri dari baris dan kolom (seperti tabel) dan dapat menyimpan data dari berbagai jenis (termasuk karakter, bilangan bulat, bilangan real, data kategorikal, dan lainnya).

<p align="center">
<img src="https://www.w3resource.com/w3r_images/pandas-data-frame.svg" width="600" height="300">
<p align="center"><b>Gambar 2. DataFrame Pandas</b></p>
<br>

* <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series">Series</a> merupakan kolom dari sebuah tabel yang bersifat homogen atau mempunyai elemen dengan tipe data yang sejenis.


<p align="center">
<img src="https://datagy.io/wp-content/uploads/2022/12/Understanding-Pandas-Series-and-DataFrames-1024x576.png" width="550" height="300">
<p align="center"><b>Gambar 3. Series VS DataFrame</b></p>
<br>

* Gabungan beberapa Series yang mempunyai banyak baris yang sama dapat membentuk sebuah DataFrame atau berlaku sebaliknya pada sebuah DataFrame dapat dipecah (di-<i>slicing</i> satu kolom) membentuk sebuah Series.<br><br>

# **Data Manipulation**

Data Manipulation adalah sebuah metode pengorganisasian data agar lebih mudah dibaca, terstruktur dan agar lebih mudah diolah untuk kebutuhan lain kedepannya. Beberapa hal yang biasa dilakukan saat data manipulation adalah sebagai berikut :


<ul>1️⃣ Column selections</ul>
<ul>2️⃣ Filter the data</ul>
<ul>3️⃣ Create a new column or change it</ul>
<ul>4️⃣ Drop a column</ul>
<ul>5️⃣ Apply custom functions</ul>
<ul>6️⃣ Join / Merge the data</ul>
<ul>7️⃣ etc</ul>

## **4. Data Extraction**

* Dalam konteks data extraction, Pandas dapat digunakan untuk membaca data dari berbagai sumber, seperti file CSV, Excel, SQL database, dan lainnya, dan mengubahnya menjadi DataFrames untuk analisis lebih lanjut.

* Beberapa fungsi dan metode Pandas yang umum digunakan untuk data extraction adalah sebagai berikut:

<ul>
<code><a href="https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html">pd.read_csv()</a></code>: Digunakan untuk membaca data dari file CSV dan mengonversinya menjadi DataFrame.

<code><a href="https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html">pd.read_excel()</a></code>: Membaca data dari file Excel dan membuat DataFrame dari lembar kerja atau tabel tertentu.

<code><a href="https://pandas.pydata.org/docs/reference/api/pandas.read_sql.html">pd.read_sql()</a></code>: Mengambil data dari basis data SQL menggunakan SQL query dan menyimpannya dalam bentuk DataFrame.
</ul>
<br>

_docs : https://pandas.pydata.org/docs/reference/io.html_

### 👨‍💻 Task 4.1

Untuk melakukan proses ekstraksi data, lakukan instruksi berikut :     

1.   Pada bagian kiri google colab, klik **Files** 🗂️
2.   Lalu klik **Upload to session storage** ↑
3.   Pilih file excel dengan judul **Data Telco Churn.xlsx** lalu upload
4.   Tunggu hingga file terunggah

### 👨‍💻 Task 4.2

Setelah file berhasil terunggah, lakukan pembacaan data dengan pandas. Eksekusi perintah

<p align="center"><code><b>pd.read_excel('nama_file_excel')</b></code></p>

lalu assign ke DataFrame yang diberi nama **data_telco**
<br><br>

docs : _https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html_

In [136]:
# Task 4.2 - Ekstraksi data excel dengan pandas
# url = 'https://raw.githubusercontent.com/bachtiyarma/Material/main/Dataset/Telco-Churn/Data%20Telco%20Churned.xlsx'


data_telco = pd.read_excel(r"X:\save\back\DATA BELAJAR AMMAR\Data Analyst DQLab Bootcamp\CODE\Sesi 10\Data Telco Churned.xlsx")

### 👨‍💻 Task 4.3

Tampilkan data hasil ekstraksi dengan mengeksekusi perintah

<p align="center"><code><b>display(nama_dataframe)</b></code></p>

Ketika dieksekusi maka akan muncul tampilan seperti berikut

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-Python/pandas_display_df.png" width="100%">

In [137]:
# Task 4.3 - Tampilkan DataFrame

display(data_telco)

,customer_id,open_date,gender,age,married,number_of_dependents,satisfaction_score,cltv,number_of_referrals,tenure_in_months,offer,phone_service,internet_service,internet_type,contract,payment_method,monthly_charge,total_revenue,customer_status,churn_category,churn_reason
0,1989-PRJHP,05/08/2023,Male,75.00,Yes,0.00,1,2377,1.00,27.00,NaN,Yes,Yes,Fiber Optic,Month-to-Month,Bank Withdrawal,"$ 75,5","$ 2180,15",Churned,Competitor,Competitor had better devices
1,7216-EWTRS,07/04/2025,Female,78.00,Yes,0.00,1,3128,4.00,1.00,NaN,Yes,Yes,Fiber Optic,Month-to-Month,Bank Withdrawal,"$ 100,8","$ 118,15",Churned,Attitude,Attitude of service provider
2,3269-ATYWD,05/14/2022,Male,79.00,No,0.00,1,4892,0.00,39.00,Offer C,Yes,Yes,Fiber Optic,Month-to-Month,Bank Withdrawal,"$ 95,65","$ 5544,32",Churned,Other,Don't know
3,8510-AWCXC,07/20/2024,NaN,NaN,NaN,NaN,1,3269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Churned,Attitude,Attitude of support person
4,9907-SWKKF,07/12/2025,Female,69.00,No,0.00,1,4842,0.00,1.00,Offer E,No,Yes,DSL,Month-to-Month,Credit Card,"$ 25,05","$ 25,05",Churned,Competitor,Competitor had better devices
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7041,0856-NAOES,02/13/2025,Male,29.00,No,0.00,5,2191,0.00,6.00,Offer E,Yes,Yes,DSL,Month-to-Month,Credit Card,"$ 60,9","$ 688,12",Stayed,NaN,NaN
7042,6549-BTYPG,08/14/2020,Female,19.00,Yes,0.00,5,5784,5.00,60.00,NaN,No,Yes,DSL,Two Year,Credit Card,"$ 60,8","$ 3603,45",Stayed,NaN,NaN
7043,5146-YYFRZ,01/12/2020,Male,32.00,No,0.00,5,6212,0.00,67.00,Offer A,Yes,No,NaN,Two Year,Bank Withdrawal,"$ 19,95","$ 2338,19",Stayed,NaN,NaN
7044,5351-QESIO,07/20/2025,Male,64.00,No,2.00,5,4276,0.00,1.00,Offer E,No,Yes,Cable,Month-to-Month,Mailed Check,"$ 24,2","$ 24,2",Joined,NaN,NaN
7045,5568-DMXZS,12/15/2024,Female,36.00,No,0.00,5,5227,0.00,8.00,Offer E,Yes,Yes,Cable,Month-to-Month,Bank Withdrawal,"$ 65,45","$ 853,41",Stayed,NaN,NaN

## **5. Parts Of DataFrame**

Untuk lebih memahami objek DataFrame, perlu diketahui bahwa DataFrame terdiri dari tiga komponen sebagai atribut berikut :

<ul>1️⃣ DataFrame<b>.values</b> : Nilai - nilai yang tertera pada DataFrame</ul>
<ul>2️⃣ DataFrame<b>.columns</b> : Nama kolom yang ada pada DataFrame</ul>
<ul>3️⃣ DataFrame<b>.index</b>   : Nama atau nomor index pada DataFrame</ul>

### 👨‍💻 Task 5.1

Pada DataFrame yang telah dibuat pada Task 4 (**data_telco**), coba tampilkan list nama kolomnya!

*Expected Output :*    

```
Index(['customer_id', 'open_date', 'gender', 'age', 'married',
       'number_of_dependents', 'satisfaction_score', 'customer_status', 'cltv',
       'number_of_referrals', 'tenure_in_months', 'offer', 'phone_service',
       'internet_service', 'internet_type', 'contract', 'payment_method',
       'monthly_charge', 'total_revenue', 'churn_category', 'churn_reason'],
      dtype='object')
```

In [138]:
# Task 5.1 - Tampilkan nama kolom
print(data_telco.columns)

Index(['customer_id', 'open_date', 'gender', 'age', 'married',
       'number_of_dependents', 'satisfaction_score', 'cltv',
       'number_of_referrals', 'tenure_in_months', 'offer', 'phone_service',
       'internet_service', 'internet_type', 'contract', 'payment_method',
       'monthly_charge', 'total_revenue', 'customer_status', 'churn_category',
       'churn_reason'],
      dtype='object')

### 👨‍💻 Task 5.2

Pada DataFrame yang telah dibuat pada Task 4 (**data_telco**), tampilkan juga indexnya!

*Expected Output :*    

```
RangeIndex(start=0, stop=7046, step=1)
```

In [139]:
# Task 5.2 - Tampilkan index baris

print(data_telco.index)

RangeIndex(start=0, stop=7046, step=1)

## **6. Inspecting Data Information**

* Untuk dapat menginspeksi informasi umum pada data dapat menggunakan sintaks berikut

<p align="center"><code><b>DataFrame.info()</b></code></p>

<ul>Ketika dijalankan, sintaks tersebut akan menghasilkan output informasi umum pada data seperti banyak kolom, nama kolom beserta tipe data dan jumlah data tak kosong (<i>non-null value</i>)</ul><br>

docs : _https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html_

### 👨‍💻 Task 6.1

Pada DataFrame **data_telco**, inspeksi informasi umumnya! Setelah itu coba uraikan informasi apa yang bisa didapatkan setelah melakukan inspeksi informasi umum pada data tersebut!

*Expected Output :*  

```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7046 entries, 0 to 7045
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   customer_id           7046 non-null   object        
 1   open_date             7046 non-null   datetime64[ns]
 2   gender                7044 non-null   object        
 3   age                   7044 non-null   float64       
 4   married               7044 non-null   object        
 5   number_of_dependents  7044 non-null   float64       
 6   satisfaction_score    7046 non-null   int64         
 7   customer_status       7046 non-null   object        
 8   cltv                  7046 non-null   int64         
 9   number_of_referrals   7044 non-null   float64       
 10  tenure_in_months      7044 non-null   float64       
 11  offer                 3166 non-null   object        
 12  phone_service         7044 non-null   object        
 13  internet_service      7044 non-null   object        
 14  internet_type         5518 non-null   object        
 15  contract              7044 non-null   object        
 16  payment_method        7044 non-null   object        
 17  monthly_charge        7044 non-null   object        
 18  total_revenue         7044 non-null   object        
 19  churn_category        1870 non-null   object        
 20  churn_reason          1870 non-null   object        
dtypes: datetime64[ns](1), float64(4), int64(2), object(14)
memory usage: 1.1+ MB
```

In [140]:
# Task 6.1 - Tampilkan informasi umum pada data_telco
print(data_telco.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7046 entries, 0 to 7045
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           7045 non-null   object
 1   open_date             7046 non-null   object
 2   gender                7044 non-null   object
 3   age                   7044 non-null   float64
 4   married               7044 non-null   object
 5   number_of_dependents  7044 non-null   float64
 6   satisfaction_score    7046 non-null   int64
 7   cltv                  7046 non-null   int64
 8   number_of_referrals   7044 non-null   float64
 9   tenure_in_months      7044 non-null   float64
 10  offer                 3166 non-null   object
 11  phone_service         7044 non-null   object
 12  internet_service      7044 non-null   object
 13  internet_type         5518 non-null   object
 14  contract              7044 non-null   object
 15  payment_method        7044 non-null   object
 16  monthly_charge        7044 non-null   object
 17  total_revenue         7044 non-null   object
 18  customer_status       7046 non-null   object
 19  churn_category        1870 non-null   object
 20  churn_reason          1870 non-null   object
dtypes: float64(4), int64(2), object(15)
memory usage: 1.1+ MB
None

## **7. Mengakses Series**

* Ketika ingin mengakses Series dari DataFrame dengan tujuan untuk mengambil, memproses, atau menganalisis data di satu kolom tertentu gunakan aturan berikut

<p align="center"><code><b>DataFrame[nama_kolom]</b></code></p>

### 👨‍💻 Task 7.1

Pada DataFrame **data_telco**, tampilkan kolom customer_id saja

*Expected Output :*

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-Python/pandas_display_series.png" width="15%">

In [141]:
# Task 7.1 - Akses kolom customer_id pada data_telco
data_telco['customer_id']

0       1989-PRJHP
1       7216-EWTRS
2       3269-ATYWD
3       8510-AWCXC
4       9907-SWKKF
           ...
7041    0856-NAOES
7042    6549-BTYPG
7043    5146-YYFRZ
7044    5351-QESIO
7045    5568-DMXZS
Name: customer_id, Length: 7046, dtype: object

In [142]:
# Gunakan fungsi type untuk memeriksa tipe data
display(type(data_telco['customer_id'])) # Series saja
display(type(data_telco)) #DataFrame keseluruhan

pandas.core.series.Series

pandas.core.frame.DataFrame

## **8. Mengakses Beberapa Kolom**

* Untuk mengakses beberapa kolom terpilih sekaligus, gunakan cara berikut

<p align="center"><code><b>DataFrame[list_nama_kolom]</b></code></p>

<ul><i>Note : Definisikan dulu kolom yang ingin diakses</i></ul>

### 👨‍💻 Task 8.1

Pada DataFrame **data_telco**, tampilkan kolom *customer_id, gender, age* dan *married* saja untuk mendapatkan gambaran demografi pelanggan

*Expected Output :*

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-Python/pandas_display_selected_cols.png" width="30%">

In [143]:
# Task 8.1 - Tampilkan beberapa kolom yang disebutkan

# Definsikan kolom yang akan ditampilkan
selected_cols = ['customer_id','gender','age','married']

# Tampilkan hasilnya
display(data_telco[selected_cols])

     customer_id  gender   age married
0     1989-PRJHP    Male 75.00     Yes
1     7216-EWTRS  Female 78.00     Yes
2     3269-ATYWD    Male 79.00      No
3     8510-AWCXC     NaN   NaN     NaN
4     9907-SWKKF  Female 69.00      No
...          ...     ...   ...     ...
7041  0856-NAOES    Male 29.00      No
7042  6549-BTYPG  Female 19.00     Yes
7043  5146-YYFRZ    Male 32.00      No
7044  5351-QESIO    Male 64.00      No
7045  5568-DMXZS  Female 36.00      No

[7046 rows x 4 columns]

In [144]:
display(data_telco[['customer_id','gender','age','married']])

     customer_id  gender   age married
0     1989-PRJHP    Male 75.00     Yes
1     7216-EWTRS  Female 78.00     Yes
2     3269-ATYWD    Male 79.00      No
3     8510-AWCXC     NaN   NaN     NaN
4     9907-SWKKF  Female 69.00      No
...          ...     ...   ...     ...
7041  0856-NAOES    Male 29.00      No
7042  6549-BTYPG  Female 19.00     Yes
7043  5146-YYFRZ    Male 32.00      No
7044  5351-QESIO    Male 64.00      No
7045  5568-DMXZS  Female 36.00      No

[7046 rows x 4 columns]

## **9. Menambahkan Kolom Baru**

* Menambahkan kolom baru pada DataFrame berguna untuk menyimpan hasil perhitungan, transformasi, atau informasi tambahan yang berasal dari data yang sudah ada atau dari sumber lain. Untuk menambahkan kolom baru dengan operasi tertentu gunakan aturan

<p align="center"><code><b>DataFrame[nama_kolom_baru] = ...</b></code></p><br>

<ul><li>Operasi yang bisa dilakukan untuk tipe data <b>numerik</b><br></li>

<table>
<thead>
<tr>
<th>Operator / Fungsi</th>
<th>Deskripsi</th>
<th>Contoh</th>
</tr>
</thead>
<tbody>

<tr>
<td><code>+</code> atau <code>add()</code></td>
<td>Menjumlahkan nilai antar Series/DataFrame (atau dengan skalar)</td>
<td><code>s1 + s2</code> atau <code>s1.add(s2)</code></td>
</tr>

<tr>
<td><code>-</code> atau <code>sub()</code></td>
<td>Mengurangkan nilai antar Series/DataFrame (atau dengan skalar)</td>
<td><code>s1 - s2</code> atau <code>s1.sub(s2)</code></td>
</tr>

<tr>
<td><code>*</code> atau <code>mul()</code></td>
<td>Mengalikan nilai antar Series/DataFrame (atau dengan skalar)</td>
<td><code>s1 * s2</code> atau <code>s1.mul(s2)</code></td>
</tr>

<tr>
<td><code>/</code> atau <code>truediv()</code></td>
<td>Membagi nilai antar Series/DataFrame (hasil float)</td>
<td><code>s1 / s2</code> atau <code>s1.truediv(s2)</code></td>
</tr>

<tr>
<td><code>//</code> atau <code>floordiv()</code></td>
<td>Pembagian dengan pembulatan ke bawah (integer division)</td>
<td><code>s1 // s2</code> atau <code>s1.floordiv(s2)</code></td>
</tr>

<tr>
<td><code>%</code> atau <code>mod()</code></td>
<td>Mengambil sisa hasil bagi (modulus)</td>
<td><code>s1 % s2</code> atau <code>s1.mod(s2)</code></td>
</tr>

<tr>
<td><code>**</code> atau <code>pow()</code></td>
<td>Pangkat (eksponensial)</td>
<td><code>s1 ** 2</code> atau <code>s1.pow(2)</code></td>
</tr>

<tr>
<td><code>abs()</code></td>
<td>Mengambil nilai absolut</td>
<td><code>s.abs()</code></td>
</tr>

<tr>
<td><code>round(decimals=n)</code></td>
<td>Membulatkan angka ke jumlah desimal tertentu</td>
<td><code>s.round(2)</code></td>
</tr>

<tr>
<td><code>mean()</code></td>
<td>Menghitung rata-rata</td>
<td><code>s.mean()</code></td>
</tr>

<tr>
<td><code>sum()</code></td>
<td>Menjumlahkan semua nilai</td>
<td><code>s.sum()</code></td>
</tr>

<tr>
<td><code>prod()</code></td>
<td>Mengalikan semua nilai</td>
<td><code>s.prod()</code></td>
</tr>

<tr>
<td><code>min()</code> / <code>max()</code></td>
<td>Mengambil nilai minimum / maksimum</td>
<td><code>s.min()</code> / <code>s.max()</code></td>
</tr>

<tr>
<td><code>cumsum()</code></td>
<td>Menjumlahkan kumulatif</td>
<td><code>s.cumsum()</code></td>
</tr>

<tr>
<td><code>cumprod()</code></td>
<td>Perkalian kumulatif</td>
<td><code>s.cumprod()</code></td>
</tr>

<tr>
<td><code>diff(periods=n)</code></td>
<td>Selisih antar elemen (default 1 baris)</td>
<td><code>s.diff()</code></td>
</tr>

<tr>
<td><code>pct_change()</code></td>
<td>Menghitung persentase perubahan antar nilai</td>
<td><code>s.pct_change()</code></td>
</tr>

<tr>
<td><code>clip(lower, upper)</code></td>
<td>Memotong nilai di luar rentang tertentu</td>
<td><code>s.clip(0, 100)</code></td>
</tr>

<tr>
<td><code>add(other, fill_value=0)</code></td>
<td>Menjumlahkan sambil mengganti nilai NaN dengan default</td>
<td><code>s1.add(s2, fill_value=0)</code></td>
</tr>

</tbody>
</table>
</ul>
<br>
<ul><li>Operasi yang bisa dilakukan untuk tipe data <b>string</b><br></li>
<table>
<thead>
<tr>
<th>Fungsi</th>
<th>Deskripsi</th>
<th>Contoh</th>
</tr>
</thead>
<tbody>

<tr>
<td><code>str.lower()</code></td>
<td>Mengubah semua huruf menjadi huruf kecil</td>
<td><code>s.str.lower()</code> → <code>'abc'</code></td>
</tr>

<tr>
<td><code>str.upper()</code></td>
<td>Mengubah semua huruf menjadi huruf besar</td>
<td><code>s.str.upper()</code> → <code>'ABC'</code></td>
</tr>

<tr>
<td><code>str.title()</code></td>
<td>Mengubah huruf pertama tiap kata menjadi kapital</td>
<td><code>'hello world'</code> → <code>'Hello World'</code></td>
</tr>

<tr>
<td><code>str.strip()</code></td>
<td>Menghapus spasi di awal dan akhir string</td>
<td><code>'  data '</code> → <code>'data'</code></td>
</tr>

<tr>
<td><code>str.replace(pat, repl)</code></td>
<td>Mengganti teks dengan teks lain</td>
<td><code>s.str.replace('a', 'o')</code></td>
</tr>

<tr>
<td><code>str.contains(pat)</code></td>
<td>Memeriksa apakah string mengandung pola tertentu (regex)</td>
<td><code>s.str.contains('abc')</code></td>
</tr>

<tr>
<td><code>str.startswith(pat)</code></td>
<td>Memeriksa apakah string diawali pola tertentu</td>
<td><code>s.str.startswith('A')</code></td>
</tr>

<tr>
<td><code>str.endswith(pat)</code></td>
<td>Memeriksa apakah string diakhiri pola tertentu</td>
<td><code>s.str.endswith('.com')</code></td>
</tr>

<tr>
<td><code>str.len()</code></td>
<td>Menghitung panjang tiap string</td>
<td><code>s.str.len()</code> → <code>[5, 3, 7]</code></td>
</tr>

<tr>
<td><code>str.split(pat)</code></td>
<td>Memisahkan string berdasarkan delimiter</td>
<td><code>'a,b,c'</code> → <code>['a','b','c']</code></td>
</tr>

<tr>
<td><code>str.cat(sep=' ')</code></td>
<td>Menggabungkan string dengan pemisah tertentu</td>
<td><code>s.str.cat(sep=' ')</code></td>
</tr>

<tr>
<td><code>str.extract(pat)</code></td>
<td>Menangkap pola dengan regex dan hasilkan kolom baru</td>
<td><code>s.str.extract(r'(\d+)')</code></td>
</tr>

<tr>
<td><code>str.findall(pat)</code></td>
<td>Menemukan semua kecocokan pola (regex) di setiap elemen</td>
<td><code>s.str.findall(r'\d+')</code></td>
</tr>

<tr>
<td><code>str.zfill(width)</code></td>
<td>Menambahkan nol di depan hingga panjang tertentu</td>
<td><code>'42'</code> → <code>'00042'</code></td>
</tr>

<tr>
<td><code>str.pad(width, fillchar=' ')</code></td>
<td>Menambahkan karakter tertentu di kiri/kanan</td>
<td><code>'A'</code> → <code>'  A  '</code></td>
</tr>

<tr>
<td><code>str.get(i)</code></td>
<td>Mengambil elemen indeks ke-i dari list/string</td>
<td><code>s.str.get(0)</code></td>
</tr>

<tr>
<td><code>str.join(sep)</code></td>
<td>Menggabungkan elemen list menjadi string</td>
<td><code>s.str.join('-')</code> → <code>'a-b-c'</code></td>
</tr>

<tr>
<td><code>str.replace(rgx, repl, regex=True)</code></td>
<td>Mengganti teks menggunakan ekspresi reguler</td>
<td><code>s.str.replace(r'\d+', '', regex=True)</code></td>
</tr>

<tr>
<td><code>str.wrap(width)</code></td>
<td>Membungkus teks menjadi beberapa baris</td>
<td><code>s.str.wrap(10)</code></td>
</tr>

<tr>
<td><code>str.normalize('NFKD')</code></td>
<td>Menormalkan karakter Unicode</td>
<td><code>s.str.normalize('NFKD')</code></td>
</tr>

</tbody>
</table>
</ul>

### 👨‍💻 Task 9.1

Asumsikan bahwa rataan pendapatan bulanan yang diperoleh perusahaan telco dihitung berdasarkan rumus

$$
\text{avg_revenue_in_month} = \frac{\text{total_revenue}}{\text{tenure_in_month}}
$$

Tambahkan kolom tersebut ke dalam data_telco, lalu tampilkan kolom customer_id, tenure_in_months, total_revenue, avg_revenue_in_month pada data_telco!

*Expected Output :*

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-Python/pandas_display_add_newcol.png" width="50%">

In [145]:
data_telco

,customer_id,open_date,gender,age,married,number_of_dependents,satisfaction_score,cltv,number_of_referrals,tenure_in_months,offer,phone_service,internet_service,internet_type,contract,payment_method,monthly_charge,total_revenue,customer_status,churn_category,churn_reason
0,1989-PRJHP,05/08/2023,Male,75.00,Yes,0.00,1,2377,1.00,27.00,NaN,Yes,Yes,Fiber Optic,Month-to-Month,Bank Withdrawal,"$ 75,5","$ 2180,15",Churned,Competitor,Competitor had better devices
1,7216-EWTRS,07/04/2025,Female,78.00,Yes,0.00,1,3128,4.00,1.00,NaN,Yes,Yes,Fiber Optic,Month-to-Month,Bank Withdrawal,"$ 100,8","$ 118,15",Churned,Attitude,Attitude of service provider
2,3269-ATYWD,05/14/2022,Male,79.00,No,0.00,1,4892,0.00,39.00,Offer C,Yes,Yes,Fiber Optic,Month-to-Month,Bank Withdrawal,"$ 95,65","$ 5544,32",Churned,Other,Don't know
3,8510-AWCXC,07/20/2024,NaN,NaN,NaN,NaN,1,3269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Churned,Attitude,Attitude of support person
4,9907-SWKKF,07/12/2025,Female,69.00,No,0.00,1,4842,0.00,1.00,Offer E,No,Yes,DSL,Month-to-Month,Credit Card,"$ 25,05","$ 25,05",Churned,Competitor,Competitor had better devices
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7041,0856-NAOES,02/13/2025,Male,29.00,No,0.00,5,2191,0.00,6.00,Offer E,Yes,Yes,DSL,Month-to-Month,Credit Card,"$ 60,9","$ 688,12",Stayed,NaN,NaN
7042,6549-BTYPG,08/14/2020,Female,19.00,Yes,0.00,5,5784,5.00,60.00,NaN,No,Yes,DSL,Two Year,Credit Card,"$ 60,8","$ 3603,45",Stayed,NaN,NaN
7043,5146-YYFRZ,01/12/2020,Male,32.00,No,0.00,5,6212,0.00,67.00,Offer A,Yes,No,NaN,Two Year,Bank Withdrawal,"$ 19,95","$ 2338,19",Stayed,NaN,NaN
7044,5351-QESIO,07/20/2025,Male,64.00,No,2.00,5,4276,0.00,1.00,Offer E,No,Yes,Cable,Month-to-Month,Mailed Check,"$ 24,2","$ 24,2",Joined,NaN,NaN
7045,5568-DMXZS,12/15/2024,Female,36.00,No,0.00,5,5227,0.00,8.00,Offer E,Yes,Yes,Cable,Month-to-Month,Bank Withdrawal,"$ 65,45","$ 853,41",Stayed,NaN,NaN

In [146]:
#Hapus simbol currency dan ubah koma menjadi titik
data_telco['total_revenue'] = data_telco['total_revenue'].str.replace('$', '')
data_telco['total_revenue'] = data_telco['total_revenue'].str.replace(',', '.')

# Lakukan konversi tipe data
data_telco['total_revenue'] = data_telco['total_revenue'].astype(pd.Float64Dtype())

# Perikasa kembali hasilnya
data_telco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7046 entries, 0 to 7045
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           7045 non-null   object
 1   open_date             7046 non-null   object
 2   gender                7044 non-null   object
 3   age                   7044 non-null   float64
 4   married               7044 non-null   object
 5   number_of_dependents  7044 non-null   float64
 6   satisfaction_score    7046 non-null   int64
 7   cltv                  7046 non-null   int64
 8   number_of_referrals   7044 non-null   float64
 9   tenure_in_months      7044 non-null   float64
 10  offer                 3166 non-null   object
 11  phone_service         7044 non-null   object
 12  internet_service      7044 non-null   object
 13  internet_type         5518 non-null   object
 14  contract              7044 non-null   object
 15  payment_method        7044 non-null   object
 16  monthly_charge        7044 non-null   object
 17  total_revenue         7044 non-null   Float64
 18  customer_status       7046 non-null   object
 19  churn_category        1870 non-null   object
 20  churn_reason          1870 non-null   object
dtypes: Float64(1), float64(4), int64(2), object(14)
memory usage: 1.1+ MB

In [147]:
# Task 9.1 - Tambahkan kolom avg_revenue_in_month

# Lakukan perhitungan
data_telco['avg_revenue_in_month'] = (data_telco['total_revenue'] / data_telco['tenure_in_months'])

# Tampilkan hasilnya
selected = ['customer_id','total_revenue','tenure_in_months','avg_revenue_in_month']
display(data_telco[selected])

     customer_id  total_revenue  tenure_in_months  avg_revenue_in_month
0     1989-PRJHP        2180.15             27.00                 80.75
1     7216-EWTRS         118.15              1.00                118.15
2     3269-ATYWD        5544.32             39.00                142.16
3     8510-AWCXC           <NA>               NaN                  <NA>
4     9907-SWKKF          25.05              1.00                 25.05
...          ...            ...               ...                   ...
7041  0856-NAOES         688.12              6.00                114.69
7042  6549-BTYPG        3603.45             60.00                 60.06
7043  5146-YYFRZ        2338.19             67.00                 34.90
7044  5351-QESIO          24.20              1.00                 24.20
7045  5568-DMXZS         853.41              8.00                106.68

[7046 rows x 4 columns]

### 👨‍💻 Task 9.2

**Apakah bisa mengubah nilai dari kolom yang sudah ada (_exsiting column_)?**

Pada kolom customer_status coba ubah penulisannya menjadi <a href="https://en.wikipedia.org/wiki/Letter_case"><i>uppercase</i></a>, lakukan *assignment* ke kolom yang sama dan tampilkan hasil perubahannya!

*Expected Output :*

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-Python/pandas_display_str_upper.png" width="15%">

In [154]:
display(data_telco['customer_status'])

0       Churned
1       Churned
2       Churned
3       Churned
4       Churned
         ...
7041     Stayed
7042     Stayed
7043     Stayed
7044     Joined
7045     Stayed
Name: customer_status, Length: 7046, dtype: object

In [155]:
data_telco['customer_status'].head(2)

0    Churned
1    Churned
Name: customer_status, dtype: object

In [156]:
# Task 9.2 - Uppercase pada kolom customer_status

# Ubah nilainya
data_telco['customer_status'] = data_telco['customer_status'].str.upper()

# Tampilkan hasilnya
display(data_telco)

,customer_id,open_date,gender,age,married,number_of_dependents,satisfaction_score,cltv,number_of_referrals,tenure_in_months,offer,phone_service,internet_service,internet_type,contract,payment_method,monthly_charge,total_revenue,customer_status,churn_category,churn_reason,avg_revenue_in_month
0,1989-PRJHP,05/08/2023,Male,75.00,Yes,0.00,1,2377,1.00,27.00,NaN,Yes,Yes,Fiber Optic,Month-to-Month,Bank Withdrawal,"$ 75,5",2180.15,CHURNED,Competitor,Competitor had better devices,80.75
1,7216-EWTRS,07/04/2025,Female,78.00,Yes,0.00,1,3128,4.00,1.00,NaN,Yes,Yes,Fiber Optic,Month-to-Month,Bank Withdrawal,"$ 100,8",118.15,CHURNED,Attitude,Attitude of service provider,118.15
2,3269-ATYWD,05/14/2022,Male,79.00,No,0.00,1,4892,0.00,39.00,Offer C,Yes,Yes,Fiber Optic,Month-to-Month,Bank Withdrawal,"$ 95,65",5544.32,CHURNED,Other,Don't know,142.16
3,8510-AWCXC,07/20/2024,NaN,NaN,NaN,NaN,1,3269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,CHURNED,Attitude,Attitude of support person,<NA>
4,9907-SWKKF,07/12/2025,Female,69.00,No,0.00,1,4842,0.00,1.00,Offer E,No,Yes,DSL,Month-to-Month,Credit Card,"$ 25,05",25.05,CHURNED,Competitor,Competitor had better devices,25.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7041,0856-NAOES,02/13/2025,Male,29.00,No,0.00,5,2191,0.00,6.00,Offer E,Yes,Yes,DSL,Month-to-Month,Credit Card,"$ 60,9",688.12,STAYED,NaN,NaN,114.69
7042,6549-BTYPG,08/14/2020,Female,19.00,Yes,0.00,5,5784,5.00,60.00,NaN,No,Yes,DSL,Two Year,Credit Card,"$ 60,8",3603.45,STAYED,NaN,NaN,60.06
7043,5146-YYFRZ,01/12/2020,Male,32.00,No,0.00,5,6212,0.00,67.00,Offer A,Yes,No,NaN,Two Year,Bank Withdrawal,"$ 19,95",2338.19,STAYED,NaN,NaN,34.90
7044,5351-QESIO,07/20/2025,Male,64.00,No,2.00,5,4276,0.00,1.00,Offer E,No,Yes,Cable,Month-to-Month,Mailed Check,"$ 24,2",24.20,JOINED,NaN,NaN,24.20
7045,5568-DMXZS,12/15/2024,Female,36.00,No,0.00,5,5227,0.00,8.00,Offer E,Yes,Yes,Cable,Month-to-Month,Bank Withdrawal,"$ 65,45",853.41,STAYED,NaN,NaN,106.68

## **10. Sorting Row**

Menemukan data yang menarik dalam sebuah DataFrame seringkali lebih mudah jika dilakukan pengurutan baris datanya. Pengurutan dibagi menjadi dua yakni pengurutan secara `Ascending` (pengurutan naik A → Z) dan juga pengurutan secara `Descending` (pengurutan turun Z → A). Eksekusi sintaks berikut :

<p align="center"><code><b>DataFrame.sort_values(by, ascending=True, ignore_index=False)</b></code></p>

Jika ingin mengurutkan DataFrame pandas dengan memperhatikan argumen

<ul>
<li><b><i>by</i></b> sebagai satu atau lebih kolom yang ingin dijadikan patokan pengurutan</li>

<li><b><i>ascending</i></b> dapat diisikan True jika ingin terurut naik atau False jika ingin terurut turun (default : True)</li>

<li><b><i>ignore_index</i></b> dapat diisikan True jika ingin index masih terurut atau False jika indexnya masih dipertahankan sesuai data awal (dafault : False)</li>

</ul><br>

docs : <i>https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html</i>

### 👨‍💻 Task 10.1

Pada **data_telco** coba periksa apakah datanya sudah terurut berdasarkan kolom open_date? Jika belum urutkan datanya berdasarkan open_date paling awal hingga paling baru (latest date)

*Expected Output :*

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-Python/pandas_display_sortvalues.png" width="100%">

In [172]:
# Task 10.1 - Urutkan data berdasarkan open_date secara ascending

# Urutkan datanya
data_telco = data_telco.sort_values(by='open_date', ascending=True)
# Tampilkan hasilnya
display(data_telco)

,customer_id,open_date,gender,age,married,number_of_dependents,satisfaction_score,cltv,number_of_referrals,tenure_in_months,offer,phone_service,internet_service,internet_type,contract,payment_method,monthly_charge,total_revenue,customer_status,churn_category,churn_reason,avg_revenue_in_month
0,1150-WFARN,01/01/2020,Female,59.00,Yes,0.00,1,5516,1.00,67.00,NaN,Yes,Yes,Fiber Optic,Two Year,Credit Card,"$ 108,75",9310.25,CHURNED,Competitor,Competitor had better devices,138.96
1,2452-KDRRH,01/01/2020,Male,76.00,No,0.00,4,5269,0.00,67.00,NaN,Yes,Yes,Fiber Optic,Two Year,Credit Card,"$ 101,4",9444.00,STAYED,NaN,NaN,140.96
2,2143-LJULT,01/01/2020,Female,55.00,Yes,0.00,5,5887,1.00,67.00,NaN,Yes,No,NaN,Two Year,Credit Card,"$ 25,25",4100.93,STAYED,NaN,NaN,61.21
3,6980-CDGFC,01/01/2020,Female,57.00,Yes,0.00,5,5972,5.00,67.00,Offer A,Yes,No,NaN,One Year,Bank Withdrawal,"$ 20,85",1857.37,STAYED,NaN,NaN,27.72
4,5174-ITUMV,01/01/2020,Male,37.00,Yes,2.00,5,5666,0.00,67.00,Offer A,Yes,Yes,Fiber Optic,One Year,Bank Withdrawal,"$ 105,4",9601.11,STAYED,NaN,NaN,143.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7040,7929-DMBCV,12/26/2023,Female,45.00,Yes,0.00,3,4741,6.00,20.00,Offer D,Yes,Yes,Fiber Optic,Month-to-Month,Mailed Check,$ 81,1911.50,STAYED,NaN,NaN,95.58
7043,7337-CINUD,12/26/2024,Female,48.00,Yes,3.00,4,5206,6.00,8.00,NaN,Yes,No,NaN,Two Year,Bank Withdrawal,"$ 19,5",296.95,STAYED,NaN,NaN,37.12
7044,4544-RXFMG,12/26/2024,Male,48.00,Yes,2.00,3,4184,1.00,8.00,Offer E,Yes,Yes,DSL,One Year,Credit Card,"$ 43,45",399.74,STAYED,NaN,NaN,49.97
7042,8388-DMKAE,12/26/2024,Female,41.00,No,0.00,5,2653,0.00,8.00,Offer E,Yes,No,NaN,Two Year,Mailed Check,"$ 20,25",301.53,STAYED,NaN,NaN,37.69
7045,1849-RJYIG,12/26/2024,Female,43.00,No,0.00,3,5862,0.00,8.00,NaN,Yes,Yes,DSL,Month-to-Month,Bank Withdrawal,$ 60,861.99,STAYED,NaN,NaN,107.75

### 👨‍💻 Task 10.2

Sudah terurut berdasarkan kolom open_date? Menarik! Sekarang perhatikan index-nya apakah berantakan? Bisa bantu sesuaikan?

*Expected Output :*

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-Python/pandas_display_sortvalues_ignoreidx.png" width="100%">

In [171]:
# Task 10.2 - Urutkan data berdasarkan open_date secara ascending dan atur indexnya

# Urutkan data dan atur indexnya
data_telco = data_telco.sort_values(by='open_date', ascending=True, ignore_index=True)
# Tampilkan hasilnya
display(data_telco)

,customer_id,open_date,gender,age,married,number_of_dependents,satisfaction_score,cltv,number_of_referrals,tenure_in_months,offer,phone_service,internet_service,internet_type,contract,payment_method,monthly_charge,total_revenue,customer_status,churn_category,churn_reason,avg_revenue_in_month
0,1150-WFARN,01/01/2020,Female,59.00,Yes,0.00,1,5516,1.00,67.00,NaN,Yes,Yes,Fiber Optic,Two Year,Credit Card,"$ 108,75",9310.25,CHURNED,Competitor,Competitor had better devices,138.96
1,2452-KDRRH,01/01/2020,Male,76.00,No,0.00,4,5269,0.00,67.00,NaN,Yes,Yes,Fiber Optic,Two Year,Credit Card,"$ 101,4",9444.00,STAYED,NaN,NaN,140.96
2,2143-LJULT,01/01/2020,Female,55.00,Yes,0.00,5,5887,1.00,67.00,NaN,Yes,No,NaN,Two Year,Credit Card,"$ 25,25",4100.93,STAYED,NaN,NaN,61.21
3,6980-CDGFC,01/01/2020,Female,57.00,Yes,0.00,5,5972,5.00,67.00,Offer A,Yes,No,NaN,One Year,Bank Withdrawal,"$ 20,85",1857.37,STAYED,NaN,NaN,27.72
4,5174-ITUMV,01/01/2020,Male,37.00,Yes,2.00,5,5666,0.00,67.00,Offer A,Yes,Yes,Fiber Optic,One Year,Bank Withdrawal,"$ 105,4",9601.11,STAYED,NaN,NaN,143.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7041,0947-MUGVO,12/26/2023,Male,71.00,Yes,0.00,1,5849,1.00,20.00,NaN,Yes,Yes,Fiber Optic,Month-to-Month,Bank Withdrawal,"$ 73,65",1570.90,CHURNED,Competitor,Competitor had better devices,78.55
7042,8388-DMKAE,12/26/2024,Female,41.00,No,0.00,5,2653,0.00,8.00,Offer E,Yes,No,NaN,Two Year,Mailed Check,"$ 20,25",301.53,STAYED,NaN,NaN,37.69
7043,7337-CINUD,12/26/2024,Female,48.00,Yes,3.00,4,5206,6.00,8.00,NaN,Yes,No,NaN,Two Year,Bank Withdrawal,"$ 19,5",296.95,STAYED,NaN,NaN,37.12
7044,4544-RXFMG,12/26/2024,Male,48.00,Yes,2.00,3,4184,1.00,8.00,Offer E,Yes,Yes,DSL,One Year,Credit Card,"$ 43,45",399.74,STAYED,NaN,NaN,49.97
7045,1849-RJYIG,12/26/2024,Female,43.00,No,0.00,3,5862,0.00,8.00,NaN,Yes,Yes,DSL,Month-to-Month,Bank Withdrawal,$ 60,861.99,STAYED,NaN,NaN,107.75

In [173]:
# Task 10.2 - Urutkan data berdasarkan open_date secara ascending dan atur indexnya

# Urutkan data dan atur indexnya
data_telco = data_telco.sort_values(by=['open_date','customer_id'], ascending=True, ignore_index=True)
# Tampilkan hasilnya
display(data_telco)

,customer_id,open_date,gender,age,married,number_of_dependents,satisfaction_score,cltv,number_of_referrals,tenure_in_months,offer,phone_service,internet_service,internet_type,contract,payment_method,monthly_charge,total_revenue,customer_status,churn_category,churn_reason,avg_revenue_in_month
0,0379-DJQHR,01/01/2020,Male,60.00,Yes,0.00,3,4219,1.00,67.00,NaN,Yes,Yes,DSL,Two Year,Credit Card,"$ 81,35",8430.35,STAYED,NaN,NaN,125.83
1,1150-WFARN,01/01/2020,Female,59.00,Yes,0.00,1,5516,1.00,67.00,NaN,Yes,Yes,Fiber Optic,Two Year,Credit Card,"$ 108,75",9310.25,CHURNED,Competitor,Competitor had better devices,138.96
2,2143-LJULT,01/01/2020,Female,55.00,Yes,0.00,5,5887,1.00,67.00,NaN,Yes,No,NaN,Two Year,Credit Card,"$ 25,25",4100.93,STAYED,NaN,NaN,61.21
3,2452-KDRRH,01/01/2020,Male,76.00,No,0.00,4,5269,0.00,67.00,NaN,Yes,Yes,Fiber Optic,Two Year,Credit Card,"$ 101,4",9444.00,STAYED,NaN,NaN,140.96
4,2990-OGYTD,01/01/2020,Female,41.00,Yes,0.00,5,5037,1.00,67.00,Offer A,Yes,Yes,DSL,Two Year,Bank Withdrawal,"$ 86,15",6098.25,STAYED,NaN,NaN,91.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7041,7929-DMBCV,12/26/2023,Female,45.00,Yes,0.00,3,4741,6.00,20.00,Offer D,Yes,Yes,Fiber Optic,Month-to-Month,Mailed Check,$ 81,1911.50,STAYED,NaN,NaN,95.58
7042,1849-RJYIG,12/26/2024,Female,43.00,No,0.00,3,5862,0.00,8.00,NaN,Yes,Yes,DSL,Month-to-Month,Bank Withdrawal,$ 60,861.99,STAYED,NaN,NaN,107.75
7043,4544-RXFMG,12/26/2024,Male,48.00,Yes,2.00,3,4184,1.00,8.00,Offer E,Yes,Yes,DSL,One Year,Credit Card,"$ 43,45",399.74,STAYED,NaN,NaN,49.97
7044,7337-CINUD,12/26/2024,Female,48.00,Yes,3.00,4,5206,6.00,8.00,NaN,Yes,No,NaN,Two Year,Bank Withdrawal,"$ 19,5",296.95,STAYED,NaN,NaN,37.12
7045,8388-DMKAE,12/26/2024,Female,41.00,No,0.00,5,2653,0.00,8.00,Offer E,Yes,No,NaN,Two Year,Mailed Check,"$ 20,25",301.53,STAYED,NaN,NaN,37.69

##**11. Conditions**

* Salah satu teknik paling sederhana untuk menemukan bagian mana dari kumpulan data yang menarik adalah menemukan subset baris yang cocok dengan beberapa kriteria untuk difilter atau dipilih. Untuk melakukan hal ini cukup mudah yakni dengan menuliskan kondisi seperti berikut

<p align="center"><code><b>DataFrame[conditions]</b></code></p>
<br>

* Conditions perlu menggunakan operator pembanding (_comparison operators_) atau operator keanggotaan (_membership operators_):

<ul><table>
<thead>
<tr>
<th>Operator</th>
<th>Nama / Fungsi</th>
<th>Contoh</th>
</tr>
</thead>
<tbody>

<tr>
<td><code>==</code></td>
<td>Equal to — membandingkan kesetaraan nilai</td>
<td><code>5 == 5</code></td>
</tr>

<tr>
<td><code>!=</code></td>
<td>Not equal to — membandingkan ketidaksamaan nilai</td>
<td><code>5 != 3</code></td>
</tr>

<tr>
<td><code>&gt;</code></td>
<td>Greater than — lebih besar dari</td>
<td><code>10 &gt; 5</code></td>
</tr>

<tr>
<td><code>&lt;</code></td>
<td>Less than — lebih kecil dari</td>
<td><code>2 &lt; 8</code></td>
</tr>

<tr>
<td><code>&gt;=</code></td>
<td>Greater than or equal to — lebih besar atau sama dengan</td>
<td><code>7 &gt;= 7</code></td>
</tr>

<tr>
<td><code>&lt;=</code></td>
<td>Less than or equal to — lebih kecil atau sama dengan</td>
<td><code>3 &lt;= 4</code></td>
</tr>

<tr>
<td><code>is</code></td>
<td>Identitas — membandingkan apakah dua objek adalah objek yang sama (bukan hanya nilainya)</td>
<td><code>a is b</code></td>
</tr>

<tr>
<td><code>is not</code></td>
<td>Kebalikan dari <code>is</code> — True jika dua objek berbeda</td>
<td><code>a is not b</code></td>
</tr>

<tr>
<td><code>in</code></td>
<td>Membership — memeriksa apakah elemen ada di dalam koleksi (list, tuple, string, dll)</td>
<td><code>'a' in 'data'</code></td>
</tr>

<tr>
<td><code>not in</code></td>
<td>Kebalikan dari <code>in</code> — memeriksa apakah elemen tidak ada di dalam koleksi</td>
<td><code>'x' not in 'data'</code></td>
</tr>

</tbody>
</table>
</ul>
<br>

* Conditions dapat dibentuk dari 1 atau lebih kriteria boolean dan dihubungkan dengan operator logika
<br>

<ul><table>
<thead>
<tr>
<th>Operator</th>
<th>Nama / Fungsi</th>
<th>Nilai Kebenaran</th>
</tr>
</thead>
<tbody>

<tr>
<td><code>&amp;</code></td>
<td>Bitwise AND — operasi logika berbasis bit antar nilai biner</td>
<td>Bernilai benar jika semua kondisi terpenuhi</td>
</tr>

<tr>
<td><code>|</code></td>
<td>Bitwise OR — operasi logika OR berbasis bit</td>
<td>Bernilai benar jika salah satu kondisi terpenuhi</td>
</tr>

<tr>
<td><code>~</code></td>
<td>Bitwise NOT — membalikkan bit (komplemen biner)</td>
<td>Negasi / kebalikan</td>
</tr>

</tbody>
</table>
</ul>

### 👨‍💻 Task 11.1

Pada **data_telco**, tampilkan data customer yang CHURNED saja

*Expected Output :*

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-Python/pandas_display_condition1.png" width="100%">

In [175]:
# Task 11.1 - Filter data customer_status = CHURNED

# Buat kondisi
# condition1 = data_telco['customer_status'] == 'CHURNED'
condition1 = (data_telco['customer_status'].str.upper() == 'CHURNED')

# Filter dan Tampilkan hasilnya saja
display(data_telco[condition1])

,customer_id,open_date,gender,age,married,number_of_dependents,satisfaction_score,cltv,number_of_referrals,tenure_in_months,offer,phone_service,internet_service,internet_type,contract,payment_method,monthly_charge,total_revenue,customer_status,churn_category,churn_reason,avg_revenue_in_month
1,1150-WFARN,01/01/2020,Female,59.00,Yes,0.00,1,5516,1.00,67.00,NaN,Yes,Yes,Fiber Optic,Two Year,Credit Card,"$ 108,75",9310.25,CHURNED,Competitor,Competitor had better devices,138.96
14,2091-RFFBA,01/01/2023,Female,70.00,No,0.00,1,2560,0.00,31.00,NaN,Yes,Yes,Fiber Optic,Month-to-Month,Bank Withdrawal,"$ 73,9",2695.48,CHURNED,Attitude,Attitude of support person,86.95
22,1925-TIBLE,01/01/2025,Female,62.00,Yes,0.00,1,3887,1.00,7.00,NaN,Yes,Yes,Fiber Optic,Month-to-Month,Bank Withdrawal,"$ 86,5",760.77,CHURNED,Competitor,Competitor offered higher download speeds,108.68
23,2575-GFSOE,01/01/2025,Female,25.00,Yes,0.00,2,5672,1.00,7.00,Offer E,Yes,Yes,Fiber Optic,Month-to-Month,Bank Withdrawal,$ 69,569.55,CHURNED,Attitude,Attitude of service provider,81.36
29,4580-TMHJU,01/02/2022,Female,57.00,Yes,0.00,2,2152,3.00,43.00,NaN,Yes,Yes,DSL,Month-to-Month,Bank Withdrawal,"$ 56,15",4101.05,CHURNED,Other,Don't know,95.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7020,8818-XYFCQ,12/25/2022,Male,39.00,Yes,0.00,1,5026,1.00,32.00,Offer C,Yes,Yes,Fiber Optic,Month-to-Month,Credit Card,"$ 99,55",4353.07,CHURNED,Competitor,Competitor made better offer,136.03
7022,1567-DSCIC,12/25/2024,Male,59.00,No,0.00,1,2632,0.00,8.00,NaN,Yes,Yes,Fiber Optic,Month-to-Month,Bank Withdrawal,$ 94,964.77,CHURNED,Dissatisfaction,Product dissatisfaction,120.60
7023,3235-ETOOB,12/25/2024,Male,51.00,Yes,0.00,2,3683,1.00,8.00,NaN,Yes,Yes,Fiber Optic,Month-to-Month,Bank Withdrawal,"$ 74,5",993.18,CHURNED,Competitor,Competitor made better offer,124.15
7035,1550-LOAHA,12/26/2022,Female,53.00,Yes,0.00,2,4017,1.00,32.00,NaN,Yes,Yes,Fiber Optic,Month-to-Month,Bank Withdrawal,"$ 84,15",3785.31,CHURNED,Dissatisfaction,Limited range of services,118.29
7037,0947-MUGVO,12/26/2023,Male,71.00,Yes,0.00,1,5849,1.00,20.00,NaN,Yes,Yes,Fiber Optic,Month-to-Month,Bank Withdrawal,"$ 73,65",1570.90,CHURNED,Competitor,Competitor had better devices,78.55

### 👨‍💻 Task 11.2

Pada **data_telco**, tampilkan data customer yang CHURNED namun nilai Customer Life-Time Value nya lebih dari 5000!

*Expected Output :*

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/main/Image/Materi-Python/pandas_display_condition2.png" width="100%">

In [178]:
# Task 11.2 - Filter data customer_status = CHURNED dan customer life time value > 5000

# Buat kondisi
condition1 = (data_telco['customer_status'].str.upper() == 'CHURNED')
condition2 = (data_telco['cltv'] > 5000)

# Filter dan Tampilkan hasilnya saja
display(data_telco[condition1 & condition2])

,customer_id,open_date,gender,age,married,number_of_dependents,satisfaction_score,cltv,number_of_referrals,tenure_in_months,offer,phone_service,internet_service,internet_type,contract,payment_method,monthly_charge,total_revenue,customer_status,churn_category,churn_reason,avg_revenue_in_month
1,1150-WFARN,01/01/2020,Female,59.00,Yes,0.00,1,5516,1.00,67.00,NaN,Yes,Yes,Fiber Optic,Two Year,Credit Card,"$ 108,75",9310.25,CHURNED,Competitor,Competitor had better devices,138.96
23,2575-GFSOE,01/01/2025,Female,25.00,Yes,0.00,2,5672,1.00,7.00,Offer E,Yes,Yes,Fiber Optic,Month-to-Month,Bank Withdrawal,$ 69,569.55,CHURNED,Attitude,Attitude of service provider,81.36
56,7912-SYRQT,01/03/2025,Female,35.00,No,0.00,2,5514,0.00,7.00,Offer E,Yes,Yes,Fiber Optic,Month-to-Month,Bank Withdrawal,"$ 75,1",685.88,CHURNED,Competitor,Competitor offered more data,97.98
57,8563-IIOXK,01/03/2025,Male,24.00,Yes,0.00,1,5651,4.00,7.00,Offer E,Yes,Yes,DSL,One Year,Bank Withdrawal,"$ 49,75",584.28,CHURNED,Competitor,Competitor offered higher download speeds,83.47
92,3005-NFMTA,01/06/2021,Male,73.00,No,0.00,2,5543,0.00,55.00,Offer B,Yes,Yes,Fiber Optic,Month-to-Month,Bank Withdrawal,"$ 98,8",6108.90,CHURNED,Price,Price too high,111.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6988,5233-GEEAX,12/23/2024,Male,65.00,No,0.00,1,5971,0.00,8.00,Offer E,No,Yes,DSL,Month-to-Month,Bank Withdrawal,"$ 29,4",221.90,CHURNED,Competitor,Competitor had better devices,27.74
6989,7234-FECYN,12/23/2024,Female,78.00,No,0.00,3,5546,0.00,8.00,NaN,Yes,Yes,Fiber Optic,Month-to-Month,Bank Withdrawal,"$ 101,35",1132.34,CHURNED,Attitude,Attitude of support person,141.54
6990,9889-TMAHG,12/23/2024,Male,66.00,No,0.00,1,5084,0.00,8.00,NaN,Yes,Yes,Fiber Optic,Month-to-Month,Credit Card,"$ 100,3",924.91,CHURNED,Competitor,Competitor had better devices,115.61
7020,8818-XYFCQ,12/25/2022,Male,39.00,Yes,0.00,1,5026,1.00,32.00,Offer C,Yes,Yes,Fiber Optic,Month-to-Month,Credit Card,"$ 99,55",4353.07,CHURNED,Competitor,Competitor made better offer,136.03
7037,0947-MUGVO,12/26/2023,Male,71.00,Yes,0.00,1,5849,1.00,20.00,NaN,Yes,Yes,Fiber Optic,Month-to-Month,Bank Withdrawal,"$ 73,65",1570.90,CHURNED,Competitor,Competitor had better devices,78.55

##**12. Aggregation**

Agregasi data merupakan serangkaian proses yang dilakukan untuk melakukan pengumpulan data dan dinyatakan dalam bentuk ringkasan sebagai contoh menghitung total yang dikelompokkan berdasarkan kategori tertentu, dsb.

Untuk melakukan agregasi gunakan sintaks berikut

<p align="center"><code><b>DataFrame.groupby(by, as_index).agg(kolom_hasil_aggregasi = (kolom_dihitung, jenis_agregasi))</b></code></p>

Jenis agregasi :
* sum = Menghitung total data
* mean = Menghitung rataan data
* max = Menghitung nilai maksimum data
* min = Menghitung nilai minimum data
* nunique = Menghitung jumlah data unik data
* count = Menghitung banyak data

### 👨‍💻 Task 12.1

Pada **data_telco**, hitung jumlah data tiap statusnya!

In [189]:
data_telco.groupby(['customer_status']).agg(total_customer=('customer_id','count'))

                 total_customer
customer_status
CHURNED                    1869
JOINED                      454
STAYED                     4722

### 👨‍💻 Task 12.2

Pada **data_telco**, hitung proporsi tiap statusnya!

In [190]:
data_telco.groupby(['customer_status'], dropna = False).agg(
    total_customer=('customer_id','count'),
    avg_revenue = ('total_revenue', 'mean')
)

                 total_customer  avg_revenue
customer_status
CHURNED                    1869      1967.35
JOINED                      454       119.56
STAYED                     4722      3735.41

Data Source : <i>https://www.ibm.com/docs/en/cognos-analytics/12.0.x?topic=samples-telco-customer-churn</i> (dengan modifikasi)


---

<br>
<a href="https://www.linkedin.com/in/ammarbp/"><img src="https://img.shields.io/badge/-© 2026 Ammar Bagus Pambudi-0072b1?style=for-the-badge&logoColor=white"/></a>

<a href="https://dqlab.id/"><img src="https://dqlab.id/files/dqlab/cache/87e30118ebba5ec7d96f6ea8c9dcc10b_x_118_X_55.png" align="left" /></a>